#!/data/data/com.termux/files/usr/bin/bash
# COLORS
W="\e[0m"
R="\e[31m"
G="\e[32m"
Y="\e[33m"
B="\e[34m"
os="alpine"

XorCLi="-nographic"
  cd ${HOME}/$os &> /dev/null
  case "$os" in
    alpine)
      qemu-system-x86_64 -machine q35 -m $(free --mega|grep "Mem"|awk '{print $2}') -smp \
        cpus=$(nproc) -cpu qemu64 -vga virtio -full-screen -usb \
        -drive if=pflash,format=raw,read-only=on,file=$PREFIX/share/qemu/edk2-x86_64-code.fd \
        -netdev user,id=n1,hostfwd=tcp::2222-:22 -device virtio-net,netdev=n1 \
        $XorCLi $os.img
      ;;
  esac
 || {
  echo -en $R"E:$W $(basename $0) PATH missing ...$Y Aborting.$W"
  exit 1
}
####::: REPORT ISSUES AT https://t.me/Ivam3_Bot :::####
